{% set name = "python-goosefem" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseFEM/archive/v{{ version }}.tar.gz
  sha256: 9af6be2dee469313660c2e21827f7c3047fb9dac24bdc6da45b617f021812ad1

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - setuptools_scm
    - pip
    - pyxtensor
    - eigen
  run:
    - python

test:
  imports:
    - GooseFEM

about:
  home: https://github.com/tdegeus/GooseFEM
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: Finite element simulations.
  description: Finite element simulations.
  doc_url: https://goosefem.rtfd.io
  dev_url: https://github.com/tdegeus/GooseFEM

extra:
  recipe-maintainers:
    - tdegeus
