{% set name = "python-goosefem" %}
{% set version = "0.3.1" %}
{% set sha256 = "62431bd16cc774daa418bef8e559373946a87a79f6e5acd8c609ae47c6fe7c8a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseFEM/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
    - eigen
  run:
    - python

test:
  imports:
    - GooseFEM

about:
  home: https://github.com/tdegeus/GooseFEM
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: Finite element simulations.
  description: Finite element simulations.
  doc_url: https://goosefem.rtfd.io
  dev_url: https://github.com/tdegeus/GooseFEM

extra:
  recipe-maintainers:
    - tdegeus
