{% set name = "python-goosefem" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseFEM/archive/v{{ version }}.tar.gz
  sha256: "ed4506f0071c92557f16a500079560e05fd7c011efbc0e5ffa467b65a9336042"

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
    - eigen
  run:
    - python

test:
  imports:
    - GooseFEM

about:
  home: https://github.com/tdegeus/GooseFEM
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: Finite element simulations.
  description: Finite element simulations.
  doc_url: https://goosefem.rtfd.io
  dev_url: https://github.com/tdegeus/GooseFEM

extra:
  recipe-maintainers:
    - tdegeus
